  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=dev_postgres
        - POSTGRES_USER=dev_user
        - POSTGRES_PASSWORD=dev_password
    web:
      build: .
      command: python starter/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
    