@base = http://localhost:8000

POST {{base}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "adminc@go.com",
  "password": "berekbere"
}

###
GET {{base}}/api/quote
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTg4NzEwMDk5LCJqdGkiOiJlNmU4NTA2MjhkM2E0ZDJjOGI5YmQ5ZTA3OGJjZDlmZSIsInVzZXJfaWQiOjF9.1fo1b7f2u3pvyvsYDOx6zpBZRxdK5i__JlguOn4Qm4U

###
POST {{base}}/users/register/
Content-Type: application/json

{
  "email": "adminc@go.com",
  "password": "berekberek"
}