@base = http://localhost:8000

POST {{base}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Test for api
GET {{base}}/api/quote
Authorization: Bearer XXXXXXXXX

###
POST {{base}}/users/register/
Content-Type: application/json

{
  "email": "adminc@go.com",
  "password": "berekberek"
}